from utils import spotify_utils, io_utils

cp='./data/annotations/uspopLabels'
all_paths=list()

ids_paths1=list()
ids_paths1.append(['5ZPp1V3PufN6qhAe3rLNmb', cp + '/3_doors_down/The_Better_Life/01-Kryptonite.lab'])
ids_paths1.append(['3YMTNzrRktpHDsi6OrmZNO', cp + '/a_ha/Hunting_High_and_Low/01-Take_On_Me.lab'])
ids_paths1.append(['01iyCAUm8EvOFqVWYJ3dVX', cp + '/abba/Arrival/02-Dancing_Queen.lab'])
#ids_paths1.append(['', cp + '/abba/Live/03-I_Have_A_Dream.lab'])
#ids_paths1.append(['', cp + '/abba/Live/06-Thank_You_for_The_Music.lab'])
#ids_paths1.append(['', cp + '/abba/Live/08-Fernando.lab'])
#ids_paths1.append(['', cp + '/abba/Live/10-Super_Trouper.lab'])
ids_paths1.append(['69QHm3pustz01CJRwdo20z', cp + '/ac_dc/back_in_black/01-Hells_Bells.lab'])
ids_paths1.append(['4dDurgTN3eGyU0ghzFJ0T1', cp + '/ac_dc/back_in_black/08-Have_A_Drink_On_Me.lab'])
ids_paths1.append(['1oBTw7IkWnEUxiestsAD1V', cp + '/aerosmith/Nine_Lives/02-Falling_In_Love.lab'])
ids_paths1.append(['3t0vWl1ZOC93L0tX1fxfGU', cp + '/alanis_morissette/MTV_Unplugged/08-Ironic.lab'])
ids_paths1.append(['4yESZm57m03IVe0Ni9P07n', cp + '/alanis_morissette/MTV_Unplugged/12-Uninvited.lab'])
ids_paths1.append(['7ziHnshbknkpFLDW5yGBjO', cp + '/all_saints/All_Saints/01-Never_Ever.lab'])
ids_paths1.append(['2biWKOdQ3jXHJPTzk0ZMZD', cp + '/aqua/Aquarium/05-Doctor_Jones.lab'])
ids_paths1.append(['5Oku2oz35kTKVFIydi66nz', cp + '/backstreet_boys/Millennium/02-I_Want_It_That_Way.lab'])
ids_paths1.append(['1mutOzfgO49cWVjXt0ofqd', cp + '/backstreet_boys/Millennium/03-Show_Me_The_Meaning_Of_Being_Lonely.lab'])
ids_paths1.append(['6pfQmrU7j4qXznurAwq4n7', cp + '/backstreet_boys/Millennium/11-No_One_Else_Comes_Close.lab'])
ids_paths1.append(['6iGU74CwXuT4XVepjc9Emf', cp + '/beach_boys/Pet_Sounds/08-God_Only_Knows.lab'])
ids_paths1.append(['4kIYRtgbZyPzAWSFLdlajW', cp + '/beach_boys/Surfin_USA_Surfin_Safari/01-Surfin_Safari.lab'])
ids_paths1.append(['0wz1LjDb9ZNEYwOmDJ3Q4b', cp + '/beach_boys/Surfin_USA_Surfin_Safari/13-Surfin_USA.lab'])
all_paths.append(ids_paths1)

ids_paths2=list()
ids_paths2.append(['2oxWmwLmnVkBujTbllajwo', cp + '/beck/Mellow_Gold/01-Loser.lab'])
ids_paths2.append(['562JrM9b7jiu8LgzV62x3o', cp + '/bette_midler/The_Rose/12-The_Rose.lab'])
ids_paths2.append(['0A1QehwXuYOGcIoZHy7UTb', cp + '/billy_idol/Rebel_Yell_Expanded_Edition_/03-Eyes_Without_A_Face.lab'])
ids_paths2.append(['78WVLOP9pN0G3gRLFy1rAa', cp + '/billy_joel/Piano_Man/02-Piano_Man.lab'])
ids_paths2.append(['06RdYCp0UxsBtWsonHfSZz', cp + '/billy_joel/The_Stranger/03-Just_the_Way_You_Are.lab'])
ids_paths2.append(['2xabqm0YNQCTcPteQjJ22K', cp + '/billy_joel/The_Stranger/06-Only_the_Good_Die_Young.lab'])
ids_paths2.append(['3ILLSvTYvFjjEdbxvQumOb', cp + '/billy_joel/The_Stranger/07-She_s_Always_a_Woman.lab'])
ids_paths2.append(['0W35nxtHtFlseSojmygEsf', cp + '/black_sabbath/Paranoid/01-War_Pigs_Luke_s_Wall.lab'])
ids_paths2.append(['0TI8TP4FitVPoEHPTySx48', cp + '/black_sabbath/Paranoid/04-Iron_Man.lab'])
#ids_paths2.append(['', cp + '/blessid_union_of_souls/The_Singles/14-I_Believe.lab'])
ids_paths2.append(['0v9JiebCBHgxQYxPFUHtj5', cp + '/blink_182/Enema_Of_The_State/10-Mutt.lab'])
ids_paths2.append(['4cQJ27R11K634x5qCOwKW5', cp + '/blondie/Parallel_Lines/02-One_Way_or_Another.lab'])
ids_paths2.append(['76O0RqUHIKG7jq3LwBTUgS', cp + '/bob_marley/Exodus/01-Natural_Mystic.lab'])
ids_paths2.append(['6gOirCUz62z0mFhCJ6P5KC', cp + '/bob_marley/Exodus/06-Jamming.lab'])
ids_paths2.append(['2mKsPUojh602HvSeNt04CB', cp + '/bob_marley/Live_/05-No_Woman_No_Cry.lab'])
ids_paths2.append(['2UvvOucWTQplRKovGI4Gfn', cp + '/bon_jovi/Bon_Jovi_Remastered_/01-Runaway.lab'])
ids_paths2.append(['0gdKZTKis5hxnZdf2Zj2yf', cp + '/bon_jovi/New_Jersey/10-I_ll_Be_There_For_You.lab'])
ids_paths2.append(['3U7H63zKWLjOuFZJUmTowp', cp + '/bon_jovi/Slippery_When_Wet/02-You_Give_Love_a_Bad_Name.lab'])
ids_paths2.append(['45eF0AQGCTgkUJ3FoIYrbe', cp + '/bonnie_tyler/Faster_Than_The_Speed_Of_Night/04-Total_Eclipse_Of_The_Heart.lab'])
ids_paths2.append(['3MjUtNVVq3C8Fn0MP3zhXa', cp + '/britney_spears/_Baby_One_More_Time/01-_Babt_One_More_Time.lab'])
all_paths.append(ids_paths2)

ids_paths3=list()
ids_paths3.append(['7p9dd71JR2ucoAuO1Sy0VZ', cp + '/bryan_adams/On_A_Day_Like_Today/08-When_You_re_Gone_With_Melanie_C_.lab'])
ids_paths3.append(['4VHo8YynGTkEgFw5Xd3Lzj', cp + '/bryan_adams/Reckless/06-Summer_of_69.lab'])
ids_paths3.append(['4LOgi2TAAoKU9ImfzRrCPO', cp + '/bryan_adams/So_Far_So_Good/08-Heaven.lab'])
ids_paths3.append(['76qB2ZEZlEJAMqMqUjKusp', cp + '/bryan_adams/So_Far_So_Good/10-_Everything_I_Do_I_Do_It_For_You.lab'])
ids_paths3.append(['2DnJjbjNTV9Nd5NOa1KGba', cp + '/carly_simon/No_Secerts/03-You_re_So_Vain.lab'])
ids_paths3.append(['1nuPLLH6DukqDNmhFqPswT', cp + '/cat_stevens/Teaser_And_The_Firecat/07-Morning_Has_Broken.lab'])
ids_paths3.append(['0qBG7G94hkqEMenZxiz6S6', cp + '/celine_dion/AU_COEUR_DU_STADE/11-My_Heart_Will_Go_On.lab'])
ids_paths3.append(['2JRicL2f8tJl9TiQlH7vbJ', cp + '/celine_dion/Falling_Into_You/01-It_s_All_Coming_Back_To_Me_Now.lab'])
ids_paths3.append(['1S1TItTK7HaRDnfj1vZ80Q', cp + '/celine_dion/Falling_Into_You/03-Falling_Into_You.lab'])
ids_paths3.append(['20EpQjfV7B4ZQJkIdHO1Tw', cp + '/celine_dion/Falling_Into_You/06-All_By_Myself.lab'])
ids_paths3.append(['0eHZ7dpv4iT7bMEYDoILIa', cp + '/cher/Heart_Of_Stone/01-If_I_Could_Turn_Back_Time.lab'])
ids_paths3.append(['0KMGxYKeUzK9wc5DZCt3HT', cp + '/chicago/Chicago_X/04-If_You_Leave_Me_Now.lab'])
ids_paths3.append(['6onLnWywmbSnXDFPVY1mM6', cp + '/christina_aguilera/Christina_Aguilera/01-Genie_In_A_Bottle.lab'])
ids_paths3.append(['2iIg5LCp81QGEpnAFDT8V4', cp + '/christina_aguilera/Christina_Aguilera/02-What_A_Girl_Wants.lab'])
ids_paths3.append(['3AJwUDP919kvQ9QcozQPxg', cp + '/coldplay/Parachutes/05-Yellow.lab'])
ids_paths3.append(['2ndVw0jBHQzQ47PweEWPK3', cp + '/corrs/In_Blue/08-One_night.lab'])
ids_paths3.append(['5kWY52e7A2dH11zFeu9nzK', cp + '/cranberries/No_Need_To_Argue/04-Zombie.lab'])
ids_paths3.append(['2LawezPeJhN4AWuSB0GtAU', cp + '/creedence_clearwater_revival/Pendulum/04-Have_You_Ever_Seen_The_Rain-.lab'])
ids_paths3.append(['01Ny92qndsKIKqRPIP550K', cp + '/creedence_clearwater_revival/The_Concert/08-Proud_Mary.lab'])
ids_paths3.append(['25fowDvPAUn4hUkZKzudZp', cp + '/creedence_clearwater_revival/Willy_and_the_Poor_Boys/03-Cotton_fields.lab'])
all_paths.append(ids_paths3)

ids_paths4=list()
ids_paths4.append(['0QVgZCAnasHo3TevIz7XLW', cp + '/cyndi_lauper/Twelve_Deadly_Cyns/02-Girls_Just_Want_to_Have_Fun.lab'])
#ids_paths4.append(['', cp + '/deep_purple/Nobody_s_Perfect_Disc_2_2_/06-Smoke_On_The_Water.lab'])
ids_paths4.append(['3yUcJwYu7fXAfqMj9krY6l', cp + '/dido/No_Angel/06-Thank_You.lab'])
ids_paths4.append(['2YMM4fB2faNhpEBBZS7TdU', cp + '/dire_straits/Alchemy_Disc_1_/03-Romeo_And_Juliet.lab'])
ids_paths4.append(['4bgfMOKbX5q7XHRECffBl5', cp + '/don_mclean/Favorites_And_Rarities_-_Disc_1/02-And_I_Love_Her_So.lab'])
ids_paths4.append(['76xUPsej31Chuwzh0VpC2f', cp + '/don_mclean/Favorites_And_Rarities_-_Disc_1/04-Vincent_Starry_Starry_Night_.lab'])
ids_paths4.append(['14XWXWv5FoCbFzLksawpEe', cp + '/doors/L_A_Woman/10-Riders_On_The_Storm.lab'])
ids_paths4.append(['5uvosCdMlFdTXhoazkTI5R', cp + '/doors/The_Doors/06-Light_My_Fire.lab'])
ids_paths4.append(['3Ly5gUO0UsNl7stAzY4dRD', cp + '/elton_john/Here_There_-_Disc_II_There_Live_at_Madison_Square_Garden_/06-Daniel.lab'])
ids_paths4.append(['1sho7fki06PJIjvOmjz8wl', cp + '/elton_john/Live_in_Australia/05-Sorry_seems_to_be_the_hardest_word.lab'])
ids_paths4.append(['61ByYNSU3iHKRW2hDDNPLQ', cp + '/elton_john/Live_in_Australia/11-Candle_in_the_wind.lab'])
ids_paths4.append(['2wWwlyJseVsx4ruq0ZTF1e', cp + '/elton_john/Live_in_Australia/13-Your_song.lab'])
ids_paths4.append(['39vhxfS20BvWseZh9ldlJO', cp + '/elton_john/Too_Low_For_Zero/05-I_Guess_That_S_Why_They_Call_it_The_Blues.lab'])
ids_paths4.append(['2hON3z0PTxwx9u4zzEyFRo', cp + '/elvis_presley/Elvis_Christmas_Album/06-Santa_Bring_My_Baby_Back_To_Me_.lab'])
ids_paths4.append(['0y6DSMwFO6cLKN1XB85cGV', cp + '/enya/A_Day_Without_Rain/01-A_Day_WIthout_Rain.lab'])
ids_paths4.append(['4MJ4El9vcKHOQT2RNIhrh2', cp + '/enya/A_Day_Without_Rain/02-Wild_Child.lab'])
ids_paths4.append(['6FLwmdmW77N1Pxb1aWsZmO', cp + '/enya/A_Day_Without_Rain/03-Only_Time.lab'])
ids_paths4.append(['4UW5yJcnRrOtHdKOnBds7M', cp + '/enya/A_Day_Without_Rain/06-Flora_s_Secret.lab'])
#ids_paths4.append(['5YNUF9XA2H4FyUUX391NDs', cp + '/enya/A_Day_Without_Rain/08-Silver_Inches.lab'])
ids_paths4.append(['3v7LMTMdPYKzlXB4frwIjH', cp + '/enya/The_Memory_of_Trees/08-Tea-House_Moon.lab'])
all_paths.append(ids_paths4)

ids_paths5=list()
ids_paths5.append(['2XkWsVewOXOhSwWCQx2tR8', cp + '/enya/Watermark/01-Watermark.lab'])
ids_paths5.append(['2wh02rF6ax6DUl1MWtiKz7', cp + '/enya/Watermark/04-Storms_in_Africa.lab'])
ids_paths5.append(['4edunTZK6KcLzfPJU6mohK', cp + '/enya/Watermark/08-Evening_Falls_.lab'])
ids_paths5.append(['65m1vnzpcjWJSaE7eyUvQ3', cp + '/eric_clapton/Crossroads_2_Disc_2/01-Layla.lab'])
ids_paths5.append(['4Iy9qWvgVRyZiOPFjBbrta', cp + '/eric_clapton/Crossroads_2_Disc_4/05-Wonderful_tonight.lab'])
ids_paths5.append(['3zYsZdhveEJeui0ekhrZOv', cp + '/eric_clapton/Unplugged/04-Tears_in_Heaven.lab'])
ids_paths5.append(['1TfqLAPs4K3s2rJMoCokcS', cp + '/eurythmics/Sweet_Dreams_Are_Made_Of_This_/06-Sweet_Dreams_Are_Made_Of_This_.lab'])
ids_paths5.append(['7pN5knX62XY7SNi1WsIh5W', cp + '/everclear/So_Much_For_The_Afterglow/06-Father_Of_Mine.lab'])
ids_paths5.append(['37EJtTS7jT5WUyXGZzrwnI', cp + '/everclear/Sparkle_And_Fade/04-Santa_Monica.lab'])
ids_paths5.append(['76HnRI6IQX4YHzYTgcM0RV', cp + '/everly_brothers/The_Fabulous_Style_of/14-All_I_Have_To_Do_Is_Dream.lab'])
ids_paths5.append(['1JLn8RhQzHz3qDqsChcmBl', cp + '/foreigner/Agent_Provocateur/03-I_Want_To_Know_What_Love_Is.lab'])
ids_paths5.append(['1ymaji9iiLLfPOq91srHeH', cp + '/frank_sinatra/Come_Fly_With_Me/04-Moonlight_In_Vermont.lab'])
ids_paths5.append(['0Q0IVlqMV64kNLlwjPj0Hl', cp + '/fugees/The_Score/08-Killing_Me_Softly.lab'])
ids_paths5.append(['63nkNgHkmfgjElTEnCzKYU', cp + '/gabrielle/Rise/02-Rise.lab'])
ids_paths5.append(['1yea9mxOFUgcXOt5cgiBT6', cp + '/garbage/Garbage/03-Only_Happy_When_It_Rains.lab'])
ids_paths5.append(['4tmvNDYDxzspyUTVckmwI9', cp + '/genesis/Invisible_Touch/04-In_Too_Deep.lab'])
ids_paths5.append(['1G8jae4jD8mwkXdodqHsBM', cp + '/Goo_Goo_Dolls/A_Boy_Named_Goo/06-Name.lab'])
ids_paths5.append(['5zmaypMaWb21FUGBxbw8hT', cp + '/Goo_Goo_Dolls/Dizzy_Up_The_Girl/05-Black_Balloon.lab'])
ids_paths5.append(['7nnWIPM5hwE3DaUBkvOIpy', cp + '/Incubus/Make_Yourself/08-Drive.lab'])
ids_paths5.append(['0IaMMHVbpJ0LrRAeigWOXr', cp + '/janet_jackson/Janet/19-19_Again.lab'])
all_paths.append(ids_paths5)

ids_paths6=list()
ids_paths6.append(['0wJoRiX5K5BxlqZTolB2LD', cp + '/jimi_hendrix_experience/Are_You_Experienced/01-Purple_Haze.lab'])
ids_paths6.append(['0hig4Cf4QPSBzYjGtKmn9R', cp + '/joe_cocker/Joe_Cocker_Live/10-You_Are_So_Beautiful.lab'])
ids_paths6.append(['1WiMMuQKlVjFW2LevuPtAk', cp + '/john_denver/An_Evening_With_John_Denver_Remastered_Disc_1/11-Annie_s_Song.lab'])
ids_paths6.append(['1ydNrg5m64qFjNZA4rGx8m', cp + '/john_denver/Poems_Prayers_Promises/01-Poems_Prayers_and_Promises.lab'])
ids_paths6.append(['08ZAVXwts5Ye1PFBNo3NGS', cp + '/john_denver/Poems_Prayers_Promises/03-My_Sweet_Lady.lab'])
ids_paths6.append(['1YYhDizHx7PnDhAhko6cDS', cp + '/john_denver/Poems_Prayers_Promises/07-Take_Me_Home_Country_Roads.lab'])
ids_paths6.append(['0naWmO0bE2itsfHCuDwf4N', cp + '/kansas/Two_For_The_Show/08-Dust_In_The_Wind.lab'])
ids_paths6.append(['046MBhhgQJJghnbgZCkaAR', cp + '/leann_rimes/I_Need_You/01-I_Need_You.lab'])
ids_paths6.append(['2AogRMqARWyUP7VQ3gmSoY', cp + '/leann_rimes/I_Need_You/05-Can_t_Fight_The_Moonlight.lab'])
ids_paths6.append(['0if9el1gAypHIJ2S7zGUQP', cp + '/led_zeppelin/The_Song_Remains_The_Same_Disc_Two_/02-Stairway_To_Heaven.lab'])
ids_paths6.append(['5iwyLsQ5yjnCaRrJGyAPZM', cp + '/lionel_richie/Back_To_Front/07-Endless_Love.lab'])
ids_paths6.append(['7ndelVxF4Y8K6xg8WXUVMV', cp + '/live/Throwing_Copper/03-I_Alone.lab'])
ids_paths6.append(['5oqukcHWfqq7HGjyKwLX1y', cp + '/madonna/Bedtime_Stories/11-Take_A_Bow.lab'])
ids_paths6.append(['7ySbfLwdCwl1EM0zNCJZ38', cp + '/mariah_carey/Daydream/03-One_Sweet_Day.lab'])
ids_paths6.append(['4FCb4CUbFCMNRkI6lYc1zI', cp + '/mariah_carey/Music_Box/02-Hero.lab'])
ids_paths6.append(['0S8xKy1efKy3LvR53qe3Cq', cp + '/mariah_carey/Music_Box/03-Anytime_You_Need_A_Friend.lab'])
ids_paths6.append(['1kMOJBmpfWD9fir6st9uqS', cp + '/mariah_carey/Music_Box/07-Without_You.lab'])
ids_paths6.append(['2uT80fdyUC3tYpiF4i6VLC', cp + '/metallica/Live_Shit_Binge_And_Purge_Disc_3_/01-Nothing_Else_Matters.lab'])
ids_paths6.append(['7woW97CfcWaKtuC6W5BP2K', cp + '/michael_jackson/Dangerous/07-Heal_The_World.lab'])
ids_paths6.append(['3BovdzfaX4jb5KFQwoPfAw', cp + '/michael_jackson/Thriller/05-Beat_It.lab'])
all_paths.append(ids_paths6)

ids_paths7=list()
ids_paths7.append(['7xe1rxQLilEfk1VwfD3Jik', cp + '/mike_oldfield/Crisis/02-Moonlight_Shadow.lab'])
ids_paths7.append(['6kyxQuFD38mo4S3urD2Wkw', cp + '/muse/Showbiz/07-Unintended.lab'])
ids_paths7.append(['1Jaah2tmN9Hv81A87KZ1MU', cp + '/natalie_imbruglia/Left_of_the_Middle/01-Torn.lab'])
ids_paths7.append(['5t6OF8gDW9xFOdLaTrWW2K', cp + '/neil_diamond/Hot_August_Night_-_Disc_1/07-Sweet_Caroline.lab'])
ids_paths7.append(['2ljhsCscPaLGlIVImS8dMV', cp + '/neil_diamond/Hot_August_Night_-_Disc_1/10-Red_Red_Wine.lab'])
ids_paths7.append(['3ezNsdWCjH9dkMe0555y1X', cp + '/neil_diamond/Hot_August_Night_-_Disc_1/13-Shilo.lab'])
ids_paths7.append(['1x5twuiuKoAVzIRgKVuG2s', cp + '/neil_diamond/Hot_August_Night_Disk_2_/01-Play_Me.lab'])
ids_paths7.append(['4a5LPkFBSSmBdJJMdLRFRd', cp + '/neil_diamond/Hot_August_Night_Disk_2_/04-Song_Sung_Blue.lab'])
ids_paths7.append(['2et9DhKxEpa15rpGia5xMe', cp + '/neil_diamond/Hot_August_Night_Disk_2_/07-I_Am_I_Said.lab'])
#ids_paths7.append(['', cp + '/neil_sedaka/Neil_Sedaka_-_Tuneweaver/01-Love_Will_Keep_Us_Together.lab'])
#ids_paths7.append(['', cp + '/neil_sedaka/Neil_Sedaka_-_Tuneweaver/09-Laughter_In_The_Rain.lab'])
ids_paths7.append(['1f3yAtsJtY87CTmM8RLnxf', cp + '/Nirvana/Nevermind/01-Smells_Like_Teen_Spirit.lab'])
ids_paths7.append(['36bOT34EdRNrNhCWMwNJKu', cp + '/no_doubt/Tragic_Kingdom/03-Just_A_Girl.lab'])
ids_paths7.append(['5PsUB0ISfQxRLhF5DmI5Ks', cp + '/no_doubt/Tragic_Kingdom/10-Don_t_Speak.lab'])
ids_paths7.append(['4r8lRYnoOGdEi6YyI5OC1o', cp + '/nsync/No_Strings_Attached/01-Bye_Bye_Bye.lab'])
ids_paths7.append(['2Dp2LRrY71XIfLe3co2Qnh', cp + '/nsync/No_Strings_Attached/06-This_I_Promise_You.lab'])
#ids_paths7.append(['', cp + '/o_town/O-Town/07-All_Or_Nothing.lab'])
ids_paths7.append(['5qqabIl2vWzo9ApSC317sa', cp + '/oasis/_What_s_The_Story_Morning_Glory_/03-Wonderwall.lab'])
ids_paths7.append(['1FkoVC85Ds3mFoK0fVqEqP', cp + '/offspring/Smash/08-Self_Esteem.lab'])
#ids_paths7.append(['', cp + '/olivia_newton_john/Olivia/19-If_You_Love_Me.lab'])
#ids_paths7.append(['', cp + '/olivia_newton_john/Olivia/21-I_Honestly_Love_You.lab'])
all_paths.append(ids_paths7)

ids_paths8=list()
ids_paths8.append(['0SjhCnjTT2bXD9RtU8bFT9', cp + '/papa_roach/Infest/02-Last_Resort.lab'])
ids_paths8.append(['00NETFopF0BY2bZTstKr5C', cp + '/paul_simon/Concert_in_the_Park_Disc_1/10-Bridge_Over_Troubled_Water.lab'])
ids_paths8.append(['48XEoZjXkevT5cUmRatcQV', cp + '/paul_simon/Concert_in_the_Park_Disc_2/12-The_Sound_of_Silence.lab'])
#ids_paths8.append(['', cp + '/peter_gabriel/Secret_World_Live_Disk_1_/02-Steam.lab'])
ids_paths8.append(['4F2t297QK40XFcIHqkmLHs', cp + '/phil_collins/But_Seriously/06-I_Wish_It_Would_Rain_Down.lab'])
ids_paths8.append(['6MjfEIHOMW6MaDO3LpFcmW', cp + '/phil_collins/Face_Value_/01-In_The_Air_Tonight.lab'])
ids_paths8.append(['0qYNU0d6q2797FZwc4HXoJ', cp + '/police/Live_Disc_One_-_Orpheum_WBCN_Boston_Broadcast/08-Message_In_A_Bottle.lab'])
ids_paths8.append(['1OZIdBEhNH2tMDNcqlR0Q4', cp + '/police/Live_Disc_Two_-_Atlanta_Synchronicity_Concert/12-Every_Breath_You_Take.lab'])
ids_paths8.append(['662TT3tFX1USwRdwYnmtxN', cp + '/police/Live_Disc_Two_-_Atlanta_Synchronicity_Concert/13-Roxanne.lab'])
ids_paths8.append(['2JdzB67NvIa90K4gEZPLeX', cp + '/presidents_of_the_united_states_of_america/Presidents_of_the_United_States_of_America/03-Lump.lab'])
#ids_paths8.append(['', cp + '/procol_harum/The_Long_Goodbye/07-A_Whiter_Shade_of_Pale.lab'])
ids_paths8.append(['2RzJwBCXsS1VnjDm2jKKAa', cp + '/r_kelly/R_Disk_2_/13-I_Believe_I_Can_Fly.lab'])
ids_paths8.append(['3SVAN3BRByDmHOhKyIDxfC', cp + '/radiohead/OK_Computer/06-Karma_Police.lab'])
ids_paths8.append(['5Q30xdABnojqN3wBIhrsQp', cp + '/rem/Automatic_For_The_People/04-Everybody_Hurts.lab'])
ids_paths8.append(['4LFwNJWoj74Yd71fIr1W8x', cp + '/richard_marx/Repeat_Offender/05-Right_Here_Waiting.lab'])
ids_paths8.append(['0Ph6L4l8dYUuXFmb71Ajnd', cp + '/ricky_martin/Ricky_Martin/01-Livin_La_Vida_Loca.lab'])
ids_paths8.append(['13iyUtbSqmUnqeuyaBK04b', cp + '/rod_stewart/Absolutely_Live/15-Sailing.lab'])
ids_paths8.append(['3S0pLtHQWFYCmNE9byQcWS', cp + '/rod_stewart/Vagabond_Heart/10-Have_I_Told_You_Lately.lab'])
ids_paths8.append(['3p55Y6bZ5DdoZ1n2xfKanP', cp + '/rolling_stones/Get_Yer_Ya-Ya_s_Out_/09-Honky_Tonk_Woman.lab'])
ids_paths8.append(['00FZpAIJJjn8eVLPhWF4SN', cp + '/rolling_stones/Some_Girls/09-Beast_Of_Burden.lab'])
all_paths.append(ids_paths8)

ids_paths9=list()
ids_paths9.append(['1vxz4SLkZv2aLIWMNg2LBK', cp + '/roy_orbison/Black_and_White_Night/03-Blue_Bayou.lab'])
ids_paths9.append(['7lV0qU5T3tT0O4hypQkg6k', cp + '/roy_orbison/Black_and_White_Night/10-Crying.lab'])
ids_paths9.append(['4XwHemosziPE4xsx44mm6J', cp + '/roy_orbison/Black_and_White_Night/17-Oh_Pretty_Woman.lab'])
ids_paths9.append(['0db2p2sk1UPg92hMnSz3J8', cp + '/sarah_mclachlan/Mirrorball/05-_Adia_by_Sarah_McLachlan.lab'])
ids_paths9.append(['4omTcmDBlW55uSs6m1aVbq', cp + '/sarah_mclachlan/Mirrorball/14-_Angel_by_Sarah_McLachlan.lab'])
ids_paths9.append(['339sGo9Kq0DEW8G3tmc1ga', cp + '/selena/Dreaming_Of_You/05-Dreaming_Of_You.lab'])
ids_paths9.append(['4yxKbzUC9auTZR9rTvFOTr', cp + '/shaggy/Hotshot/05-Angel.lab'])
ids_paths9.append(['6l8EbYRtQMgKOyc1gcDHF9', cp + '/simon_and_garfunkel/Collected_Works_-_Disc_3/01-Bridge_Over_Troubled_Water.lab'])
ids_paths9.append(['1eN42Q7IWRzRBq8eW2Y2TE', cp + '/simon_and_garfunkel/Collected_Works_-_Disc_3/02-El_Condor_Pasa_If_I_Could_.lab'])
ids_paths9.append(['6QhXQOpyYvbpdbyjgAqKdY', cp + '/simon_and_garfunkel/Collected_Works_-_Disc_3/03-Cecilia.lab'])
#ids_paths9.append(['', cp + '/simon_and_garfunkel/Collected_Works_-_Disc_3/06-The_Boxer.lab'])
ids_paths9.append(['754kgU5rWscRTfvlsuEwFp', cp + '/sixpence_none_the_richer/Sixpence_None_The_Richer/04-Kiss_Me.lab'])
ids_paths9.append(['0cGG2EouYCEEC3xfa0tDFV', cp + '/soft_cell/Non_Stop_Erotic_Cabaret/02-Tainted_Love.lab'])
ids_paths9.append(['3Wfbr37CbpImpCYxA3Urae', cp + '/soundgarden/superunknown/07-Black_Hole_Sun.lab'])
ids_paths9.append(['36AWdhZIGLUTkWpJDhe7va', cp + '/spice_girls/Spice/03-2_Become_1.lab'])
ids_paths9.append(['2udw7RDkldLFIPG9WYdVtT', cp + '/stevie_wonder/Songs_In_The_Key_Of_Life_Disc_1_/05-Sir_Duke.lab'])
ids_paths9.append(['373zqV0VLz9mnrSaY9kaiX', cp + '/stevie_wonder/Songs_in_the_Key_Of_Life_Disc_2_/01-Isn_t_She_Lovely.lab'])
ids_paths9.append(['13mXFvyRyjfIjnag95Rnug', cp + '/stevie_wonder/Talking_Book/01-You_are_the_Sunshine_of_My_life.lab'])
ids_paths9.append(['1kryOQS9FQDsbYY4db5zS5', cp + '/stevie_wonder/Talking_Book/06-Superstition.lab'])
ids_paths9.append(['1exUmVPVMO5cIKSaup8qpI', cp + '/sting/Ten_Summoner_s_Tales/03-Fields_Of_Gold.lab'])
all_paths.append(ids_paths9)

ids_paths10=list()
ids_paths10.append(['1bcW30Xr00ORbniE7Vfxb4', cp + '/sublime/40oz_To_Freedom/05-Don_t_Push.lab'])
ids_paths10.append(['2Z2vOukzwOgqR4dkymRSWd', cp + '/sublime/Sublime/06-Santeria.lab'])
ids_paths10.append(['2HHtWyy5CgaQbC7XSoOb0e', cp + '/survivor/Eye_Of_The_Tiger/01-Eye_Of_The_Tiger.lab'])
ids_paths10.append(['35SiNV5YHBDsuiTtD0CIwc', cp + '/temple_of_the_dog/Temple_of_The_Dog/03-Hunger_Strike.lab'])
ids_paths10.append(['42et6fnHCw1HIPSrdPprMl', cp + '/third_eye_blind/Third_Eye_Blind/03-Semi-Charmed_Life.lab'])
ids_paths10.append(['0Ir0Esfpcg0EB6Kq8VbbAh', cp + '/tom_petty/Full_Moon_Fever/02-I_Won_t_Back_Down.lab'])
ids_paths10.append(['4kAJawkLZj4Q7N5521ofP6', cp + '/u2/The_Joshua_Tree/03-With_or_Without_You.lab'])
ids_paths10.append(['7N3PAbqfTjSEU1edb2tY8j', cp + '/van_halen/1984/02-Jump.lab'])
ids_paths10.append(['3yrSvpt2l1xhsV9Em88Pul', cp + '/van_morrison/Blowin_Your_Mind_Gold_Disc_/01-Brown_Eyed_Girl.lab'])
ids_paths10.append(['0AWkeJQmQO2VRfsVV89ym6', cp + '/vengaboys/The_Party_Album/06-We_re_Going_To_Ibiza.lab'])
ids_paths10.append(['0Svkvt5I79wficMFgaqEQJ', cp + '/weezer/Pinkerton/07-El_Scorcho.lab'])
ids_paths10.append(['29xKs5BAHlmlX1u4gzQAbJ', cp + '/weezer/Weezer_Green_Album_/03-Hash_Pipe.lab'])
ids_paths10.append(['3Pnhzf3Knhdsavx0VM2ZmG', cp + '/weezer/Weezer_Green_Album_/04-Island_In_The_Sun.lab'])
ids_paths10.append(['6yJxCltgtmGxIgKOS6ndnu', cp + '/whitney_houston/Whitney_Houston/09-Greatest_Love_Of_All.lab'])
all_paths.append(ids_paths10)



def download():
	sp = spotify_utils.initialize_spotify()
	store_path = "./data/songs/usp_"
	#io_utils.print_dict_list(billboard_index)
	i=0
	for plist in all_paths:
		for p in plist:
			print("i="+str(i))
			track_id= p[0]
			track_annotations_path= p[1]
			track_info = track_annotations_path.split('/')
			track_artist= track_info[4]
			track_title = track_info[-1][3:-4]
			store_name = store_path+track_artist+'-'+track_title+'.csv'
			segments = spotify_utils.get_segments_by_track_id(sp,track_id)
			chords = io_utils.load_annotations_file(track_annotations_path,tab_separated=False,billboard=True)
			combined=io_utils.combine_segments_annotations(segments,chords)
			io_utils.store_dict_list_to_csv(combined,store_name)
			i+=1